/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getBulkArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-bulk-archive-change',
    description: '批量归档已完成的变更。适用于归档多个并行变更。',
    instructions: `批量归档多个已完成的变更。

此技能允许你批量归档变更，通过检查代码库确定实际已实现的内容，智能地处理规格冲突。

**输入**：无需输入（提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`rd list --json\` 获取所有活跃变更。

   如果没有活跃变更，通知用户并停止。

2. **提示选择变更**

   使用 **AskUserQuestion 工具** 的多选功能让用户选择变更：
   - 显示每个变更及其 schema
   - 包含"所有变更"选项
   - 允许任意数量的选择（1 个以上即可，2 个以上是典型用例）

   **重要提示**：不要自动选择。始终让用户选择。

3. **批量验证 - 收集所有选中变更的状态**

   对于每个选中的变更，收集：

   a. **制品状态** - 运行 \`rd status --change "<name>" --json\`
      - 解析 \`schemaName\` 和 \`artifacts\` 列表
      - 记录哪些制品是 \`done\`，哪些是其他状态

   b. **任务完成情况** - 读取 \`openspec/changes/<name>/tasks.md\`
      - 统计 \`- [ ]\`（未完成）和 \`- [x]\`（已完成）的数量
      - 如果不存在任务文件，记录为"无任务"

   c. **增量规格** - 检查 \`openspec/changes/<name>/specs/\` 目录
      - 列出存在哪些 capability 规格
      - 对于每个规格，提取需求名称（匹配 \`### Requirement: <name>\` 的行）

4. **检测规格冲突**

   构建 \`capability -> [涉及该 capability 的变更]\` 的映射：

   \`\`\`
   auth -> [change-a, change-b]  <- 冲突（2 个以上变更）
   api  -> [change-c]            <- 正常（仅 1 个变更）
   \`\`\`

   当 2 个或更多选中的变更具有相同 capability 的增量规格时，即存在冲突。

5. **智能解决冲突**

   **对于每个冲突**，调查代码库：

   a. **读取增量规格**，从每个冲突变更中了解各自声称要添加/修改的内容

   b. **搜索代码库**，查找实现证据：
      - 查找实现每个增量规格需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 如果只有一个变更已实现 -> 同步该变更的规格
      - 如果两个都已实现 -> 按时间顺序应用（先旧的，新的覆盖）
      - 如果都未实现 -> 跳过规格同步，警告用户

   d. **记录解决方案**，针对每个冲突：
      - 要应用哪个变更的规格
      - 以什么顺序（如果两者都要）
      - 理由（在代码库中发现了什么）

6. **显示汇总状态表**

   显示汇总所有变更的表格：

   \`\`\`
   | 变更                | 制品    | 任务  | 规格     | 冲突    | 状态   |
   |---------------------|---------|-------|----------|---------|--------|
   | schema-management   | 完成    | 5/5   | 2 增量   | 无      | 就绪   |
   | project-config      | 完成    | 3/3   | 1 增量   | 无      | 就绪   |
   | add-oauth           | 完成    | 4/4   | 1 增量   | auth (!)| 就绪*  |
   | add-verify-skill    | 剩余 1  | 2/5   | 无       | 无      | 警告   |
   \`\`\`

   对于冲突，显示解决方案：
   \`\`\`
   * 冲突解决方案：
     - auth 规格：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对于未完成的变更，显示警告：
   \`\`\`
   警告：
   - add-verify-skill：1 个未完成的制品，3 个未完成的任务
   \`\`\`

7. **确认批量操作**

   使用 **AskUserQuestion 工具** 进行单次确认：

   - "归档 N 个变更？"根据状态提供选项
   - 选项可能包括：
     - "归档所有 N 个变更"
     - "仅归档 N 个就绪的变更（跳过未完成的）"
     - "取消"

   如果有未完成的变更，明确说明它们将带警告归档。

8. **为每个确认的变更执行归档**

   按确定的顺序处理变更（遵循冲突解决方案）：

   a. **同步规格**（如果存在增量规格）：
      - 使用 openspec-sync-specs 方式（代理驱动的智能合并）
      - 对于冲突，按已解决的顺序应用
      - 跟踪是否已同步

   b. **执行归档**：
      \`\`\`bash
      mkdir -p openspec/changes/archive
      mv openspec/changes/<name> openspec/changes/archive/YYYY-MM-DD-<name>
      \`\`\`

   c. **跟踪结果**，针对每个变更：
      - 成功：归档成功
      - 失败：归档期间出错（记录错误）
      - 跳过：用户选择不归档（如适用）

9. **显示摘要**

   显示最终结果：

   \`\`\`
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   已跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成的变更）

   规格同步摘要：
   - 4 个增量规格已同步到主规格
   - 1 个冲突已解决（auth：按时间顺序应用了两者）
   \`\`\`

   如果有任何失败：
   \`\`\`
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：仅一个已实现
\`\`\`
冲突：specs/auth/spec.md 被 [add-oauth, add-jwt] 修改

检查 add-oauth：
- 增量添加了 "OAuth Provider Integration" 需求
- 搜索代码库... 找到 src/auth/oauth.ts 实现了 OAuth 流程

检查 add-jwt：
- 增量添加了 "JWT Token Handling" 需求
- 搜索代码库... 未找到 JWT 实现

解决方案：仅 add-oauth 已实现。将仅同步 add-oauth 的规格。
\`\`\`

示例 2：两者都已实现
\`\`\`
冲突：specs/api/spec.md 被 [add-rest-api, add-graphql] 修改

检查 add-rest-api（创建于 2026-01-10）：
- 增量添加了 "REST Endpoints" 需求
- 搜索代码库... 找到 src/api/rest.ts

检查 add-graphql（创建于 2026-01-15）：
- 增量添加了 "GraphQL Schema" 需求
- 搜索代码库... 找到 src/api/graphql.ts

解决方案：两者都已实现。将先应用 add-rest-api 的规格，
再应用 add-graphql 的规格（按时间顺序，新的优先）。
\`\`\`

**成功时的输出**

\`\`\`
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/
- <change-2> -> archive/YYYY-MM-DD-<change-2>/

规格同步摘要：
- N 个增量规格已同步到主规格
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功时的输出**

\`\`\`
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/

已跳过 M 个变更：
- <change-2>（用户选择不归档未完成的变更）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时的输出**

\`\`\`
## 无变更可归档

未找到活跃变更。创建新变更以开始。
\`\`\`

**注意事项**
- 允许任意数量的变更（1 个以上即可，2 个以上是典型用例）
- 始终提示选择，不要自动选择
- 尽早检测规格冲突，通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用规格
- 仅在实现缺失时跳过规格同步（警告用户）
- 确认前显示清晰的逐变更状态
- 对整个批次使用单次确认
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>
- 如果归档目标已存在，该变更失败但继续处理其他变更`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBulkArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bulk Archive',
    description: '批量归档已完成的变更',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental', 'bulk'],
    content: `批量归档多个已完成的变更。

此技能允许你批量归档变更，通过检查代码库确定实际已实现的内容，智能地处理规格冲突。

**输入**：无需输入（提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`rd list --json\` 获取所有活跃变更。

   如果没有活跃变更，通知用户并停止。

2. **提示选择变更**

   使用 **AskUserQuestion 工具** 的多选功能让用户选择变更：
   - 显示每个变更及其 schema
   - 包含"所有变更"选项
   - 允许任意数量的选择（1 个以上即可，2 个以上是典型用例）

   **重要提示**：不要自动选择。始终让用户选择。

3. **批量验证 - 收集所有选中变更的状态**

   对于每个选中的变更，收集：

   a. **制品状态** - 运行 \`rd status --change "<name>" --json\`
      - 解析 \`schemaName\` 和 \`artifacts\` 列表
      - 记录哪些制品是 \`done\`，哪些是其他状态

   b. **任务完成情况** - 读取 \`openspec/changes/<name>/tasks.md\`
      - 统计 \`- [ ]\`（未完成）和 \`- [x]\`（已完成）的数量
      - 如果不存在任务文件，记录为"无任务"

   c. **增量规格** - 检查 \`openspec/changes/<name>/specs/\` 目录
      - 列出存在哪些 capability 规格
      - 对于每个规格，提取需求名称（匹配 \`### Requirement: <name>\` 的行）

4. **检测规格冲突**

   构建 \`capability -> [涉及该 capability 的变更]\` 的映射：

   \`\`\`
   auth -> [change-a, change-b]  <- 冲突（2 个以上变更）
   api  -> [change-c]            <- 正常（仅 1 个变更）
   \`\`\`

   当 2 个或更多选中的变更具有相同 capability 的增量规格时，即存在冲突。

5. **智能解决冲突**

   **对于每个冲突**，调查代码库：

   a. **读取增量规格**，从每个冲突变更中了解各自声称要添加/修改的内容

   b. **搜索代码库**，查找实现证据：
      - 查找实现每个增量规格需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 如果只有一个变更已实现 -> 同步该变更的规格
      - 如果两个都已实现 -> 按时间顺序应用（先旧的，新的覆盖）
      - 如果都未实现 -> 跳过规格同步，警告用户

   d. **记录解决方案**，针对每个冲突：
      - 要应用哪个变更的规格
      - 以什么顺序（如果两者都要）
      - 理由（在代码库中发现了什么）

6. **显示汇总状态表**

   显示汇总所有变更的表格：

   \`\`\`
   | 变更                | 制品    | 任务  | 规格     | 冲突    | 状态   |
   |---------------------|---------|-------|----------|---------|--------|
   | schema-management   | 完成    | 5/5   | 2 增量   | 无      | 就绪   |
   | project-config      | 完成    | 3/3   | 1 增量   | 无      | 就绪   |
   | add-oauth           | 完成    | 4/4   | 1 增量   | auth (!)| 就绪*  |
   | add-verify-skill    | 剩余 1  | 2/5   | 无       | 无      | 警告   |
   \`\`\`

   对于冲突，显示解决方案：
   \`\`\`
   * 冲突解决方案：
     - auth 规格：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对于未完成的变更，显示警告：
   \`\`\`
   警告：
   - add-verify-skill：1 个未完成的制品，3 个未完成的任务
   \`\`\`

7. **确认批量操作**

   使用 **AskUserQuestion 工具** 进行单次确认：

   - "归档 N 个变更？"根据状态提供选项
   - 选项可能包括：
     - "归档所有 N 个变更"
     - "仅归档 N 个就绪的变更（跳过未完成的）"
     - "取消"

   如果有未完成的变更，明确说明它们将带警告归档。

8. **为每个确认的变更执行归档**

   按确定的顺序处理变更（遵循冲突解决方案）：

   a. **同步规格**（如果存在增量规格）：
      - 使用 openspec-sync-specs 方式（代理驱动的智能合并）
      - 对于冲突，按已解决的顺序应用
      - 跟踪是否已同步

   b. **执行归档**：
      \`\`\`bash
      mkdir -p openspec/changes/archive
      mv openspec/changes/<name> openspec/changes/archive/YYYY-MM-DD-<name>
      \`\`\`

   c. **跟踪结果**，针对每个变更：
      - 成功：归档成功
      - 失败：归档期间出错（记录错误）
      - 跳过：用户选择不归档（如适用）

9. **显示摘要**

   显示最终结果：

   \`\`\`
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   已跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成的变更）

   规格同步摘要：
   - 4 个增量规格已同步到主规格
   - 1 个冲突已解决（auth：按时间顺序应用了两者）
   \`\`\`

   如果有任何失败：
   \`\`\`
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：仅一个已实现
\`\`\`
冲突：specs/auth/spec.md 被 [add-oauth, add-jwt] 修改

检查 add-oauth：
- 增量添加了 "OAuth Provider Integration" 需求
- 搜索代码库... 找到 src/auth/oauth.ts 实现了 OAuth 流程

检查 add-jwt：
- 增量添加了 "JWT Token Handling" 需求
- 搜索代码库... 未找到 JWT 实现

解决方案：仅 add-oauth 已实现。将仅同步 add-oauth 的规格。
\`\`\`

示例 2：两者都已实现
\`\`\`
冲突：specs/api/spec.md 被 [add-rest-api, add-graphql] 修改

检查 add-rest-api（创建于 2026-01-10）：
- 增量添加了 "REST Endpoints" 需求
- 搜索代码库... 找到 src/api/rest.ts

检查 add-graphql（创建于 2026-01-15）：
- 增量添加了 "GraphQL Schema" 需求
- 搜索代码库... 找到 src/api/graphql.ts

解决方案：两者都已实现。将先应用 add-rest-api 的规格，
再应用 add-graphql 的规格（按时间顺序，新的优先）。
\`\`\`

**成功时的输出**

\`\`\`
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/
- <change-2> -> archive/YYYY-MM-DD-<change-2>/

规格同步摘要：
- N 个增量规格已同步到主规格
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功时的输出**

\`\`\`
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/

已跳过 M 个变更：
- <change-2>（用户选择不归档未完成的变更）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时的输出**

\`\`\`
## 无变更可归档

未找到活跃变更。创建新变更以开始。
\`\`\`

**注意事项**
- 允许任意数量的变更（1 个以上即可，2 个以上是典型用例）
- 始终提示选择，不要自动选择
- 尽早检测规格冲突，通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用规格
- 仅在实现缺失时跳过规格同步（警告用户）
- 确认前显示清晰的逐变更状态
- 对整个批次使用单次确认
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>
- 如果归档目标已存在，该变更失败但继续处理其他变更`
  };
}
