/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getContinueChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-continue-change',
    description: '继续处理已有的变更，创建下一个制品。当用户想要推进变更、创建下一个制品或继续工作流时使用。',
    instructions: `继续处理变更，创建下一个制品。

**输入**：可选指定变更名称。如果未提供，检查是否可以从对话上下文中推断。如果模糊或有歧义，你必须提示用户选择可用的变更。

**步骤**

1. **如果没有提供变更名称，提示选择**

   运行 \`rd list --json\` 获取按最近修改排序的可用变更列表。然后使用 **AskUserQuestion 工具** 让用户选择要处理的变更。

   展示最近修改的 3-4 个变更作为选项，显示：
   - 变更名称
   - Schema（如果有 \`schema\` 字段则显示，否则显示 "spec-driven"）
   - 状态（例如 "0/5 任务"、"完成"、"无任务"）
   - 最近修改时间（来自 \`lastModified\` 字段）

   将最近修改的变更标记为"(推荐)"，因为这很可能是用户想要继续的变更。

   **重要**：不要猜测或自动选择变更。始终让用户自己选择。

2. **检查当前状态**
   \`\`\`bash
   rd status --change "<name>" --json
   \`\`\`
   解析 JSON 以了解当前状态。响应包含：
   - \`schemaName\`：正在使用的工作流 schema（例如 "spec-driven"）
   - \`artifacts\`：制品数组及其状态（"done"、"ready"、"blocked"）
   - \`isComplete\`：布尔值，表示所有制品是否已完成

3. **根据状态采取行动**：

   ---

   **如果所有制品已完成（\`isComplete: true\`）**：
   - 向用户表示祝贺
   - 显示最终状态，包括使用的 schema
   - 建议："所有制品已创建！你现在可以实施此变更或将其归档。"
   - 停止

   ---

   **如果有制品准备创建**（状态显示 \`status: "ready"\` 的制品）：
   - 从状态输出中选择第一个 \`status: "ready"\` 的制品
   - 获取其指令：
     \`\`\`bash
     rd instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - 解析 JSON。关键字段为：
     - \`context\`：项目背景（对你的约束 - 不要包含在输出中）
     - \`rules\`：制品特定规则（对你的约束 - 不要包含在输出中）
     - \`template\`：输出文件使用的结构
     - \`instruction\`：Schema 特定指导
     - \`outputPath\`：制品写入路径
     - \`dependencies\`：需要读取以获取上下文的已完成制品
   - **创建制品文件**：
     - 读取已完成的依赖文件以获取上下文
     - 使用 \`template\` 作为结构 - 填充其章节
     - 将 \`context\` 和 \`rules\` 作为编写时的约束 - 但不要将它们复制到文件中
     - 写入到指令中指定的输出路径
   - 展示已创建的内容和现在解锁的内容
   - 创建一个制品后停止

   ---

   **如果没有制品准备就绪（全部被阻塞）**：
   - 这在使用有效 schema 的情况下不应该发生
   - 显示状态并建议检查问题

4. **创建制品后，显示进度**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`

**输出**

每次调用后，显示：
- 创建了哪个制品
- 正在使用的 Schema 工作流
- 当前进度（N/M 已完成）
- 哪些制品现在已解锁
- 提示："要继续吗？请让我继续或告诉我下一步该做什么。"

**制品创建指南**

制品类型及其用途取决于 schema。使用指令输出中的 \`instruction\` 字段来了解要创建什么。

常见制品模式：

**spec-driven schema**（proposal → specs → design → tasks）：
- **proposal.md**：如果不清楚，询问用户关于变更的内容。填写原因、变更内容、能力、影响。
  - Capabilities 章节很关键 - 列出的每个能力都需要一个 spec 文件。
- **specs/<capability>/spec.md**：为 proposal 的 Capabilities 章节中列出的每个能力创建一个 spec（使用能力名称，而非变更名称）。
- **design.md**：记录技术决策、架构和实施方法。
- **tasks.md**：将实施分解为带复选框的任务。

对于其他 schema，遵循 CLI 输出中的 \`instruction\` 字段。

**注意事项**
- 每次调用只创建一个制品
- 创建新制品前始终读取依赖制品
- 永远不要跳过制品或乱序创建
- 如果上下文不清楚，在创建前先询问用户
- 写入后验证制品文件存在再标记进度
- 使用 schema 的制品序列，不要假设特定的制品名称
- **重要**：\`context\` 和 \`rules\` 是对你的约束，不是文件的内容
  - 不要将 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制到制品中
  - 这些指导你编写什么，但不应出现在输出中`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxContinueCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Continue',
    description: '继续处理变更 - 创建下一个制品（实验性）',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `继续处理变更，创建下一个制品。

**输入**：在 \`/rd:continue\` 后可选指定变更名称（例如 \`/rd:continue add-auth\`）。如果未提供，检查是否可以从对话上下文中推断。如果模糊或有歧义，你必须提示用户选择可用的变更。

**步骤**

1. **如果没有提供变更名称，提示选择**

   运行 \`rd list --json\` 获取按最近修改排序的可用变更列表。然后使用 **AskUserQuestion 工具** 让用户选择要处理的变更。

   展示最近修改的 3-4 个变更作为选项，显示：
   - 变更名称
   - Schema（如果有 \`schema\` 字段则显示，否则显示 "spec-driven"）
   - 状态（例如 "0/5 任务"、"完成"、"无任务"）
   - 最近修改时间（来自 \`lastModified\` 字段）

   将最近修改的变更标记为"(推荐)"，因为这很可能是用户想要继续的变更。

   **重要**：不要猜测或自动选择变更。始终让用户自己选择。

2. **检查当前状态**
   \`\`\`bash
   rd status --change "<name>" --json
   \`\`\`
   解析 JSON 以了解当前状态。响应包含：
   - \`schemaName\`：正在使用的工作流 schema（例如 "spec-driven"）
   - \`artifacts\`：制品数组及其状态（"done"、"ready"、"blocked"）
   - \`isComplete\`：布尔值，表示所有制品是否已完成

3. **根据状态采取行动**：

   ---

   **如果所有制品已完成（\`isComplete: true\`）**：
   - 向用户表示祝贺
   - 显示最终状态，包括使用的 schema
   - 建议："所有制品已创建！你可以使用 \`/rd:apply\` 实施此变更，或使用 \`/rd:archive\` 将其归档。"
   - 停止

   ---

   **如果有制品准备创建**（状态显示 \`status: "ready"\` 的制品）：
   - 从状态输出中选择第一个 \`status: "ready"\` 的制品
   - 获取其指令：
     \`\`\`bash
     rd instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - 解析 JSON。关键字段为：
     - \`context\`：项目背景（对你的约束 - 不要包含在输出中）
     - \`rules\`：制品特定规则（对你的约束 - 不要包含在输出中）
     - \`template\`：输出文件使用的结构
     - \`instruction\`：Schema 特定指导
     - \`outputPath\`：制品写入路径
     - \`dependencies\`：需要读取以获取上下文的已完成制品
   - **创建制品文件**：
     - 读取已完成的依赖文件以获取上下文
     - 使用 \`template\` 作为结构 - 填充其章节
     - 将 \`context\` 和 \`rules\` 作为编写时的约束 - 但不要将它们复制到文件中
     - 写入到指令中指定的输出路径
   - 展示已创建的内容和现在解锁的内容
   - 创建一个制品后停止

   ---

   **如果没有制品准备就绪（全部被阻塞）**：
   - 这在使用有效 schema 的情况下不应该发生
   - 显示状态并建议检查问题

4. **创建制品后，显示进度**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`

**输出**

每次调用后，显示：
- 创建了哪个制品
- 正在使用的 Schema 工作流
- 当前进度（N/M 已完成）
- 哪些制品现在已解锁
- 提示："运行 \`/rd:continue\` 创建下一个制品"

**制品创建指南**

制品类型及其用途取决于 schema。使用指令输出中的 \`instruction\` 字段来了解要创建什么。

常见制品模式：

**spec-driven schema**（proposal → specs → design → tasks）：
- **proposal.md**：如果不清楚，询问用户关于变更的内容。填写原因、变更内容、能力、影响。
  - Capabilities 章节很关键 - 列出的每个能力都需要一个 spec 文件。
- **specs/<capability>/spec.md**：为 proposal 的 Capabilities 章节中列出的每个能力创建一个 spec（使用能力名称，而非变更名称）。
- **design.md**：记录技术决策、架构和实施方法。
- **tasks.md**：将实施分解为带复选框的任务。

对于其他 schema，遵循 CLI 输出中的 \`instruction\` 字段。

**注意事项**
- 每次调用只创建一个制品
- 创建新制品前始终读取依赖制品
- 永远不要跳过制品或乱序创建
- 如果上下文不清楚，在创建前先询问用户
- 写入后验证制品文件存在再标记进度
- 使用 schema 的制品序列，不要假设特定的制品名称
- **重要**：\`context\` 和 \`rules\` 是对你的约束，不是文件的内容
  - 不要将 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制到制品中
  - 这些指导你编写什么，但不应出现在输出中`
  };
}
