/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getFeedbackSkillTemplate(): SkillTemplate {
  return {
    name: 'feedback',
    description: '收集并提交用户关于 OpenSpec 的反馈，包含上下文丰富化和匿名化处理。',
    instructions: `帮助用户提交关于 OpenSpec 的反馈。

**目标**：引导用户完成反馈的收集、丰富化和提交流程，同时通过匿名化确保隐私。

**流程**

1. **从对话中收集上下文**
   - 回顾最近的对话历史以获取上下文
   - 识别当时正在执行的任务
   - 记录哪些方面做得好或不好
   - 捕获具体的痛点或好评

2. **起草丰富的反馈**
   - 创建一个清晰、描述性的标题（单句，不需要 "反馈：" 前缀）
   - 编写正文，包含：
     - 用户想要做什么
     - 发生了什么（好的或坏的）
     - 对话中的相关上下文
     - 任何具体的建议或请求

3. **匿名化敏感信息**
   - 将文件路径替换为 \`<path>\` 或通用描述
   - 将 API 密钥、令牌、机密替换为 \`<redacted>\`
   - 将公司/组织名称替换为 \`<company>\`
   - 将个人姓名替换为 \`<user>\`
   - 将特定 URL 替换为 \`<url>\`，除非是公开/相关的
   - 保留有助于理解问题的技术细节

4. **展示草稿供审批**
   - 向用户展示完整的草稿
   - 清晰地显示标题和正文
   - 在提交前请求明确的批准
   - 允许用户要求修改

5. **确认后提交**
   - 使用 \`rd feedback\` 命令提交
   - 格式：\`rd feedback "title" --body "body content"\`
   - 命令会自动添加元数据（版本、平台、时间戳）

**草稿示例**

\`\`\`
标题：制品工作流中的错误处理需要改进

正文：
我在创建新变更时遇到了制品工作流的问题。当我在创建 proposal 后尝试继续时，
系统没有清楚地提示我需要先完成 specs。

建议：添加更清晰的错误消息来解释制品工作流中的依赖链。
比如"无法创建 design.md，因为 specs 未完成（完成 0/2）。"

上下文：使用 spec-driven schema，项目路径 <path>/my-project
\`\`\`

**匿名化示例**

之前：
\`\`\`
正在处理 /Users/john/mycompany/auth-service/src/oauth.ts
使用 API 密钥失败：sk_live_abc123xyz
就职于 Acme Corp
\`\`\`

之后：
\`\`\`
正在处理 <path>/oauth.ts
使用 API 密钥失败：<redacted>
就职于 <company>
\`\`\`

**注意事项**

- 必须在提交前展示完整草稿
- 必须请求明确批准
- 必须匿名化敏感信息
- 允许用户在提交前修改草稿
- 未经用户确认不得提交
- 包含相关的技术上下文
- 保留对话特定的见解

**需要用户确认**

始终询问：
\`\`\`
这是我起草的反馈：

标题：[标题]

正文：
[正文]

这样看起来可以吗？如果你想修改我可以调整，或者直接提交。
\`\`\`

只有在用户确认后才继续提交。`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
