/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getFfChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-ff-change',
    description: '快速推进制品创建。当用户想要快速创建实施所需的所有制品而无需逐步操作时使用。',
    instructions: `快速推进制品创建 - 一次性生成开始实施所需的所有内容。

**输入**：用户的请求应包含变更名称（kebab-case 格式）或描述他们想要构建的内容。

**步骤**

1. **如果没有明确的输入，询问他们想要构建什么**

   使用 **AskUserQuestion 工具**（开放式的，不预设选项）询问：
   > "你想要处理什么变更？描述你想要构建或修复的内容。"

   从他们的描述中，派生一个 kebab-case 格式的名称（例如 "添加用户认证" → \`add-user-auth\`）。

   **重要**：在了解用户想要构建什么之前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   rd new change "<name>"
   \`\`\`
   这将在 \`openspec/changes/<name>/\` 创建一个脚手架变更。

3. **获取制品构建顺序**
   \`\`\`bash
   rd status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`：实施前需要的制品 ID 数组（例如 \`["tasks"]\`）
   - \`artifacts\`：所有制品的列表及其状态和依赖关系

4. **按顺序创建制品直到可以实施**

   使用 **TodoWrite 工具** 跟踪制品进度。

   按依赖顺序循环处理制品（先处理没有待处理依赖的制品）：

   a. **对于每个 \`ready\`（依赖已满足）的制品**：
      - 获取指令：
        \`\`\`bash
        rd instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指令 JSON 包含：
        - \`context\`：项目背景（对你的约束 - 不要包含在输出中）
        - \`rules\`：制品特定规则（对你的约束 - 不要包含在输出中）
        - \`template\`：输出文件使用的结构
        - \`instruction\`：此制品类型的 Schema 特定指导
        - \`outputPath\`：制品写入路径
        - \`dependencies\`：需要读取以获取上下文的已完成制品
      - 读取已完成的依赖文件以获取上下文
      - 使用 \`template\` 作为结构创建制品文件
      - 将 \`context\` 和 \`rules\` 作为约束 - 但不要将它们复制到文件中
      - 显示简要进度："✓ 已创建 <artifact-id>"

   b. **继续直到所有 \`applyRequires\` 制品完成**
      - 创建每个制品后，重新运行 \`rd status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中的每个制品 ID 是否在制品数组中 \`status: "done"\`
      - 当所有 \`applyRequires\` 制品完成时停止

   c. **如果制品需要用户输入**（上下文不清楚）：
      - 使用 **AskUserQuestion 工具** 进行澄清
      - 然后继续创建

5. **显示最终状态**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`

**输出**

完成所有制品后，总结：
- 变更名称和位置
- 创建的制品列表及简要描述
- 就绪状态："所有制品已创建！准备好实施。"
- 提示："运行 \`/rd:apply\` 或让我开始实施任务。"

**制品创建指南**

- 遵循 \`rd instructions\` 中每个制品类型的 \`instruction\` 字段
- Schema 定义了每个制品应包含的内容 - 遵循它
- 创建新制品前读取依赖制品以获取上下文
- 使用 \`template\` 作为输出文件的结构 - 填充其章节
- **重要**：\`context\` 和 \`rules\` 是对你的约束，不是文件的内容
  - 不要将 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制到制品中
  - 这些指导你编写什么，但不应出现在输出中

**注意事项**
- 创建实施所需的所有制品（由 schema 的 \`apply.requires\` 定义）
- 创建新制品前始终读取依赖制品
- 如果上下文严重不清楚，询问用户 - 但优先做出合理决策以保持进展
- 如果同名变更已存在，建议继续该变更
- 写入后验证每个制品文件存在再继续下一个`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxFfCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Fast Forward',
    description: '快速推进：创建变更并一次性生成实施所需的所有制品',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `快速推进制品创建 - 一次性生成开始实施所需的所有内容。

**输入**：\`/rd:ff\` 后面的参数是变更名称（kebab-case 格式），或描述用户想要构建的内容。

**步骤**

1. **如果没有提供输入，询问他们想要构建什么**

   使用 **AskUserQuestion 工具**（开放式的，不预设选项）询问：
   > "你想要处理什么变更？描述你想要构建或修复的内容。"

   从他们的描述中，派生一个 kebab-case 格式的名称（例如 "添加用户认证" → \`add-user-auth\`）。

   **重要**：在了解用户想要构建什么之前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   rd new change "<name>"
   \`\`\`
   这将在 \`openspec/changes/<name>/\` 创建一个脚手架变更。

3. **获取制品构建顺序**
   \`\`\`bash
   rd status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`：实施前需要的制品 ID 数组（例如 \`["tasks"]\`）
   - \`artifacts\`：所有制品的列表及其状态和依赖关系

4. **按顺序创建制品直到可以实施**

   使用 **TodoWrite 工具** 跟踪制品进度。

   按依赖顺序循环处理制品（先处理没有待处理依赖的制品）：

   a. **对于每个 \`ready\`（依赖已满足）的制品**：
      - 获取指令：
        \`\`\`bash
        rd instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指令 JSON 包含：
        - \`context\`：项目背景（对你的约束 - 不要包含在输出中）
        - \`rules\`：制品特定规则（对你的约束 - 不要包含在输出中）
        - \`template\`：输出文件使用的结构
        - \`instruction\`：此制品类型的 Schema 特定指导
        - \`outputPath\`：制品写入路径
        - \`dependencies\`：需要读取以获取上下文的已完成制品
      - 读取已完成的依赖文件以获取上下文
      - 使用 \`template\` 作为结构创建制品文件
      - 将 \`context\` 和 \`rules\` 作为约束 - 但不要将它们复制到文件中
      - 显示简要进度："✓ 已创建 <artifact-id>"

   b. **继续直到所有 \`applyRequires\` 制品完成**
      - 创建每个制品后，重新运行 \`rd status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中的每个制品 ID 是否在制品数组中 \`status: "done"\`
      - 当所有 \`applyRequires\` 制品完成时停止

   c. **如果制品需要用户输入**（上下文不清楚）：
      - 使用 **AskUserQuestion 工具** 进行澄清
      - 然后继续创建

5. **显示最终状态**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`

**输出**

完成所有制品后，总结：
- 变更名称和位置
- 创建的制品列表及简要描述
- 就绪状态："所有制品已创建！准备好实施。"
- 提示："运行 \`/rd:apply\` 开始实施。"

**制品创建指南**

- 遵循 \`rd instructions\` 中每个制品类型的 \`instruction\` 字段
- Schema 定义了每个制品应包含的内容 - 遵循它
- 创建新制品前读取依赖制品以获取上下文
- 使用 \`template\` 作为输出文件的结构 - 填充其章节
- **重要**：\`context\` 和 \`rules\` 是对你的约束，不是文件的内容
  - 不要将 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制到制品中
  - 这些指导你编写什么，但不应出现在输出中

**注意事项**
- 创建实施所需的所有制品（由 schema 的 \`apply.requires\` 定义）
- 创建新制品前始终读取依赖制品
- 如果上下文严重不清楚，询问用户 - 但优先做出合理决策以保持进展
- 如果同名变更已存在，询问用户是继续该变更还是创建新变更
- 写入后验证每个制品文件存在再继续下一个`
  };
}
