/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-new-change',
    description: '从零创建新变更，使用实验性制品工作流。当用户想要通过结构化的逐步方式创建新功能、修复或修改时使用。',
    instructions: `使用实验性制品驱动方法创建新变更。

**输入**：用户的请求应包含变更名称（kebab-case 格式）或描述他们想要构建的内容。

**步骤**

1. **如果没有明确的输入，询问他们想要构建什么**

   使用 **AskUserQuestion 工具**（开放式的，不预设选项）询问：
   > "你想要处理什么变更？描述你想要构建或修复的内容。"

   从他们的描述中，派生一个 kebab-case 格式的名称（例如 "添加用户认证" → \`add-user-auth\`）。

   **重要**：在了解用户想要构建什么之前，不要继续。

2. **确定工作流 schema**

   使用默认 schema（省略 \`--schema\`），除非用户明确要求不同的工作流。

   **仅在用户提到以下情况时使用不同的 schema**：
   - 特定的 schema 名称 → 使用 \`--schema <name>\`
   - "显示工作流" 或 "有哪些工作流" → 运行 \`rd schemas --json\` 并让他们选择

   **否则**：省略 \`--schema\` 使用默认值。

3. **创建变更目录**
   \`\`\`bash
   rd new change "<name>"
   \`\`\`
   仅当用户请求特定工作流时才添加 \`--schema <name>\`。
   这将在 \`openspec/changes/<name>/\` 创建一个使用所选 schema 的脚手架变更。

4. **显示制品状态**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`
   这将显示哪些制品需要创建以及哪些已准备就绪（依赖已满足）。

5. **获取第一个制品的指令**
   第一个制品取决于 schema（例如 spec-driven 中的 \`proposal\`）。
   检查状态输出以找到第一个状态为 "ready" 的制品。
   \`\`\`bash
   rd instructions <first-artifact-id> --change "<name>"
   \`\`\`
   这将输出创建第一个制品的模板和上下文。

6. **停止并等待用户指示**

**输出**

完成步骤后，总结：
- 变更名称和位置
- 正在使用的 Schema/工作流及其制品序列
- 当前状态（0/N 制品已完成）
- 第一个制品的模板
- 提示："准备好创建第一个制品了吗？描述一下这个变更是关于什么的，我会帮你起草，或者让我继续。"

**注意事项**
- 尚未创建任何制品 - 只显示指令
- 不要超出显示第一个制品模板的范围
- 如果名称无效（非 kebab-case 格式），要求提供有效名称
- 如果同名变更已存在，建议继续该变更
- 如果使用非默认工作流，传递 --schema`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: New',
    description: '使用实验性制品工作流创建新变更',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `使用实验性制品驱动方法创建新变更。

**输入**：\`/rd:new\` 后面的参数是变更名称（kebab-case 格式），或描述用户想要构建的内容。

**步骤**

1. **如果没有提供输入，询问他们想要构建什么**

   使用 **AskUserQuestion 工具**（开放式的，不预设选项）询问：
   > "你想要处理什么变更？描述你想要构建或修复的内容。"

   从他们的描述中，派生一个 kebab-case 格式的名称（例如 "添加用户认证" → \`add-user-auth\`）。

   **重要**：在了解用户想要构建什么之前，不要继续。

2. **确定工作流 schema**

   使用默认 schema（省略 \`--schema\`），除非用户明确要求不同的工作流。

   **仅在用户提到以下情况时使用不同的 schema**：
   - 特定的 schema 名称 → 使用 \`--schema <name>\`
   - "显示工作流" 或 "有哪些工作流" → 运行 \`rd schemas --json\` 并让他们选择

   **否则**：省略 \`--schema\` 使用默认值。

3. **创建变更目录**
   \`\`\`bash
   rd new change "<name>"
   \`\`\`
   仅当用户请求特定工作流时才添加 \`--schema <name>\`。
   这将在 \`openspec/changes/<name>/\` 创建一个使用所选 schema 的脚手架变更。

4. **显示制品状态**
   \`\`\`bash
   rd status --change "<name>"
   \`\`\`
   这将显示哪些制品需要创建以及哪些已准备就绪（依赖已满足）。

5. **获取第一个制品的指令**
   第一个制品取决于 schema。检查状态输出以找到第一个状态为 "ready" 的制品。
   \`\`\`bash
   rd instructions <first-artifact-id> --change "<name>"
   \`\`\`
   这将输出创建第一个制品的模板和上下文。

6. **停止并等待用户指示**

**输出**

完成步骤后，总结：
- 变更名称和位置
- 正在使用的 Schema/工作流及其制品序列
- 当前状态（0/N 制品已完成）
- 第一个制品的模板
- 提示："准备好创建第一个制品了吗？运行 \`/rd:continue\` 或描述一下这个变更是关于什么的，我会帮你起草。"

**注意事项**
- 尚未创建任何制品 - 只显示指令
- 不要超出显示第一个制品模板的范围
- 如果名称无效（非 kebab-case 格式），要求提供有效名称
- 如果同名变更已存在，建议使用 \`/rd:continue\` 代替
- 如果使用非默认工作流，传递 --schema`
  };
}
