/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-onboard',
    description: 'OpenSpec 引导式上手教程 - 带领用户完成一个完整的工作流周期，边做边学。',
    instructions: getOnboardInstructions(),
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function getOnboardInstructions(): string {
  return `引导用户完成他们的第一次完整 OpenSpec 工作流周期。这是一次教学体验——你将在他们的代码库中完成真实工作，同时解释每个步骤。

---

## 预检查

开始之前，检查 OpenSpec CLI 是否已安装：

\`\`\`bash
# Unix/macOS
rd --version 2>&1 || echo "CLI_NOT_INSTALLED"
# Windows (PowerShell)
# if (Get-Command rd -ErrorAction SilentlyContinue) { rd --version } else { echo "CLI_NOT_INSTALLED" }
\`\`\`

**如果 CLI 未安装：**
> OpenSpec CLI 未安装。请先安装，然后再回来使用 \`/rd:onboard\`。

如果未安装则在此停止。

---

## 阶段 1：欢迎

显示：

\`\`\`
## 欢迎使用 OpenSpec！

我将带你完成一个完整的变更周期——从想法到实现——使用你代码库中的真实任务。通过实践，你将学会这套工作流。

**我们将要做的事情：**
1. 选择一个小的、真实的任务
2. 简要分析问题
3. 创建一个变更（我们工作的容器）
4. 构建制品：proposal → specs → design → tasks
5. 实现任务
6. 归档已完成的变更

**预计时间：**约 15-20 分钟

让我们从找一个可以做的事情开始。
\`\`\`

---

## 阶段 2：任务选择

### 代码库分析

扫描代码库，寻找小的改进机会。查找：

1. **TODO/FIXME 注释** - 在代码文件中搜索 \`TODO\`、\`FIXME\`、\`HACK\`、\`XXX\`
2. **缺少错误处理** - 吞掉错误的 \`catch\` 块、没有 try-catch 的危险操作
3. **没有测试的函数** - 将 \`src/\` 与测试目录交叉对比
4. **类型问题** - TypeScript 文件中的 \`any\` 类型（\`: any\`、\`as any\`）
5. **调试残留** - 非调试代码中的 \`console.log\`、\`console.debug\`、\`debugger\` 语句
6. **缺少验证** - 没有验证的用户输入处理器

同时检查最近的 git 活动：
\`\`\`bash
# Unix/macOS
git log --oneline -10 2>/dev/null || echo "No git history"
# Windows (PowerShell)
# git log --oneline -10 2>$null; if ($LASTEXITCODE -ne 0) { echo "No git history" }
\`\`\`

### 呈现建议

根据分析结果，展示 3-4 个具体建议：

\`\`\`
## 任务建议

根据代码库扫描结果，以下是一些不错的入门任务：

**1. [最有前景的任务]**
   位置：\`src/path/to/file.ts:42\`
   范围：约 1-2 个文件，约 20-30 行
   推荐理由：[简要原因]

**2. [第二个任务]**
   位置：\`src/another/file.ts\`
   范围：约 1 个文件，约 15 行
   推荐理由：[简要原因]

**3. [第三个任务]**
   位置：[位置]
   范围：[估算]
   推荐理由：[简要原因]

**4. 其他想法？**
   告诉我你想做什么。

你对哪个任务感兴趣？（选择编号或描述你自己的任务）
\`\`\`

**如果没找到合适的任务：**退而询问用户想构建什么：
> 我没有在代码库中找到明显的快速改进点。有什么你想添加或修复的小功能吗？

### 范围引导

如果用户选择或描述了一个过大的任务（主要功能、需要多天的工作）：

\`\`\`
这是一个有价值的任务，但对于你的第一次 OpenSpec 流程来说可能太大了。

对于学习工作流来说，越小越好——它可以让你看到完整的周期，而不会陷入实现细节中。

**选项：**
1. **切成更小的部分** - [他们的任务] 中最小且有用的部分是什么？也许只是 [具体切片]？
2. **选择其他任务** - 其他建议中的一个，或者一个不同的小任务？
3. **坚持做这个** - 如果你真的想做这个，我们可以。只是会花更长时间。

你更倾向于哪个？
\`\`\`

如果用户坚持，允许他们继续——这是一个软性引导。

---

## 阶段 3：探索演示

任务选定后，简要演示探索模式：

\`\`\`
在创建变更之前，让我快速给你展示一下**探索模式**——这是在确定方向之前思考问题的方式。
\`\`\`

花 1-2 分钟调查相关代码：
- 阅读涉及的文件
- 如果有帮助，画一个简单的 ASCII 图
- 记录注意事项

\`\`\`
## 快速探索

[你的简要分析——发现了什么、注意事项]

┌─────────────────────────────────────────┐
│   [可选：如果有帮助的话画 ASCII 图]      │
└─────────────────────────────────────────┘

探索模式（\`/rd:explore\`）就是用于这种思考——在实现之前进行调查。当你需要思考一个问题时，随时可以使用它。

现在让我们创建一个变更来承载我们的工作。
\`\`\`

**暂停** - 等待用户确认后再继续。

---

## 阶段 4：创建变更

**解释：**
\`\`\`
## 创建变更

OpenSpec 中的"变更"是一个容器，用于存放围绕一项工作的所有思考和规划。它存在于 \`openspec/changes/<name>/\` 中，包含你的制品——proposal、specs、design、tasks。

让我为我们的任务创建一个。
\`\`\`

**操作：**创建一个派生的 kebab-case 名称的变更：
\`\`\`bash
rd new change "<derived-name>"
\`\`\`

**展示：**
\`\`\`
已创建：\`openspec/changes/<name>/\`

文件夹结构：
\`\`\`
openspec/changes/<name>/
├── proposal.md    ← 为什么做这件事（空的，我们来填充）
├── design.md      ← 怎么构建（空的）
├── specs/         ← 详细需求（空的）
└── tasks.md       ← 实现清单（空的）
\`\`\`

现在让我们填充第一个制品——proposal。
\`\`\`

---

## 阶段 5：Proposal

**解释：**
\`\`\`
## Proposal

Proposal 记录了我们**为什么**要做这个变更，以及**什么**涉及到了。它是工作的"电梯演讲"。

我将根据我们的任务起草一个。
\`\`\`

**操作：**起草 proposal 内容（先不保存）：

\`\`\`
以下是 proposal 草稿：

---

## Why

[1-2 句话解释问题/机会]

## What Changes

[将要变化的要点]

## Capabilities

### New Capabilities
- \`<capability-name>\`: [简要描述]

### Modified Capabilities
<!-- 如果修改现有行为 -->

## Impact

- \`src/path/to/file.ts\`: [什么变化]
- [其他文件（如适用）]

---

这抓住了意图吗？我可以在保存之前调整。
\`\`\`

**暂停** - 等待用户批准/反馈。

批准后，保存 proposal：
\`\`\`bash
rd instructions proposal --change "<name>" --json
\`\`\`
然后将内容写入 \`openspec/changes/<name>/proposal.md\`。

\`\`\`
Proposal 已保存。这是你的"为什么"文档——你可以随时回来完善它，随着理解的深入。

下一步：specs。
\`\`\`

---

## 阶段 6：Specs

**解释：**
\`\`\`
## Specs

Specs 以精确、可测试的方式定义了我们要构建**什么**。它们使用需求/场景格式，使预期行为非常清晰。

对于这样的小任务，我们可能只需要一个 spec 文件。
\`\`\`

**操作：**创建 spec 文件：
\`\`\`bash
# Unix/macOS
mkdir -p openspec/changes/<name>/specs/<capability-name>
# Windows (PowerShell)
# New-Item -ItemType Directory -Force -Path "openspec/changes/<name>/specs/<capability-name>"
\`\`\`

起草 spec 内容：

\`\`\`
以下是 spec：

---

## ADDED Requirements

### Requirement: <Name>

<系统应该做什么的描述>

#### Scenario: <场景名称>

- **WHEN** <触发条件>
- **THEN** <预期结果>
- **AND** <额外结果（如需要）>

---

这种格式——WHEN/THEN/AND——使需求可测试。你可以直接把它们当作测试用例来读。
\`\`\`

保存到 \`openspec/changes/<name>/specs/<capability>/spec.md\`。

---

## 阶段 7：Design

**解释：**
\`\`\`
## Design

Design 记录了我们将**如何**构建——技术决策、权衡、方案。

对于小的变更，这可能会很简短。没关系——不是每个变更都需要深入的设计讨论。
\`\`\`

**操作：**起草 design.md：

\`\`\`
以下是设计：

---

## Context

[关于当前状态的简要背景]

## Goals / Non-Goals

**Goals:**
- [我们要达到的目标]

**Non-Goals:**
- [明确排除在范围之外的]

## Decisions

### Decision 1: [关键决策]

[方案和理由的解释]

---

对于小任务，这抓住了关键决策，而不会过度设计。
\`\`\`

保存到 \`openspec/changes/<name>/design.md\`。

---

## 阶段 8：Tasks

**解释：**
\`\`\`
## Tasks

最后，我们将工作分解为实现任务——驱动 apply 阶段的复选框。

这些应该小巧、清晰、按逻辑顺序排列。
\`\`\`

**操作：**根据 specs 和 design 生成任务：

\`\`\`
以下是实现任务：

---

## 1. [类别或文件]

- [ ] 1.1 [具体任务]
- [ ] 1.2 [具体任务]

## 2. 验证

- [ ] 2.1 [验证步骤]

---

每个复选框成为 apply 阶段中的一个工作单元。准备好实现了吗？
\`\`\`

**暂停** - 等待用户确认准备实现。

保存到 \`openspec/changes/<name>/tasks.md\`。

---

## 阶段 9：Apply（实现）

**解释：**
\`\`\`
## 实现

现在我们实现每个任务，完成时勾选它们。我会逐个宣布，并偶尔说明 specs/design 如何影响了方案。
\`\`\`

**操作：**对于每个任务：

1. 宣布："正在处理任务 N：[描述]"
2. 在代码库中实现变更
3. 自然地引用 specs/design："spec 说明了 X，所以我正在做 Y"
4. 在 tasks.md 中标记完成：\`- [ ]\` → \`- [x]\`
5. 简要状态："✓ 任务 N 完成"

保持叙述简练——不要过度解释每一行代码。

所有任务完成后：

\`\`\`
## 实现完成

所有任务已完成：
- [x] 任务 1
- [x] 任务 2
- [x] ...

变更已实现！还有最后一步——让我们归档它。
\`\`\`

---

## 阶段 10：归档

**解释：**
\`\`\`
## 归档

当变更完成后，我们归档它。这会将其从 \`openspec/changes/\` 移动到 \`openspec/changes/archive/YYYY-MM-DD-<name>/\`。

归档的变更成为项目的决策历史——你随时可以找到它们来理解为什么某样东西是这样构建的。
\`\`\`

**操作：**
\`\`\`bash
rd archive "<name>"
\`\`\`

**展示：**
\`\`\`
已归档到：\`openspec/changes/archive/YYYY-MM-DD-<name>/\`

变更现在已成为你项目历史的一部分。代码在你的代码库中，决策记录被保留下来。
\`\`\`

---

## 阶段 11：回顾与下一步

\`\`\`
## 恭喜！

你刚刚完成了一个完整的 OpenSpec 周期：

1. **Explore** - 思考问题
2. **New** - 创建变更容器
3. **Proposal** - 记录 WHY
4. **Specs** - 详细定义 WHAT
5. **Design** - 决定 HOW
6. **Tasks** - 分解为步骤
7. **Apply** - 实现工作
8. **Archive** - 保留记录

同样的节奏适用于任何规模的变更——一个小修复或一个主要功能。

---

## 命令参考

**核心工作流：**

 | 命令               | 功能                             |
 |-------------------|----------------------------------|
 | \`/rd:propose\`   | 创建变更并生成所有制品            |
 | \`/rd:explore\`   | 在工作前/中思考问题               |
 | \`/rd:apply\`     | 实现变更中的任务                  |
 | \`/rd:archive\`   | 归档已完成的变更                  |

**附加命令：**

 | 命令               | 功能                                          |
 |-------------------|-----------------------------------------------|
 | \`/rd:new\`       | 开始新变更，逐步创建制品                        |
 | \`/rd:continue\`  | 继续处理已有的变更                              |
 | \`/rd:ff\`        | 快进：一次性创建所有制品                        |
 | \`/rd:verify\`    | 验证实现是否与制品匹配                          |

---

## 接下来做什么？

试试对你实际想构建的东西使用 \`/rd:propose\`。你已经掌握了节奏！
\`\`\`

---

## 优雅退出处理

### 用户想中途停止

如果用户说他们需要停止、想暂停或看起来不太投入：

\`\`\`
没问题！你的变更已保存在 \`openspec/changes/<name>/\`。

稍后要继续之前的工作：
- \`/rd:continue <name>\` - 恢复制品创建
- \`/rd:apply <name>\` - 跳转到实现（如果任务已存在）

工作不会丢失。准备好了随时回来。
\`\`\`

优雅地退出，不要施加压力。

### 用户只想看命令参考

如果用户说他们只想看命令或跳过教程：

\`\`\`
## OpenSpec 快速参考

**核心工作流：**

 | 命令                  | 功能                             |
 |----------------------|----------------------------------|
 | \`/rd:propose <name>\` | 创建变更并生成所有制品          |
 | \`/rd:explore\`       | 思考问题（不做代码变更）         |
 | \`/rd:apply <name>\`  | 实现任务                        |
 | \`/rd:archive <name>\` | 完成后归档                     |

**附加命令：**

 | 命令                   | 功能                       |
 |-----------------------|----------------------------|
 | \`/rd:new <name>\`   | 开始新变更，逐步进行         |
 | \`/rd:continue <name>\` | 继续已有的变更           |
 | \`/rd:ff <name>\`    | 快进：一次性创建所有制品     |
 | \`/rd:verify <name>\` | 验证实现                   |

试试 \`/rd:propose\` 开始你的第一个变更。
\`\`\`

优雅地退出。

---

## 注意事项

- **在关键转换点遵循 EXPLAIN → DO → SHOW → PAUSE 模式**（探索后、proposal 草稿后、任务后、归档后）
- **实现期间保持叙述简练**——教学但不说教
- **不要跳过阶段**，即使变更很小——目标是教授工作流
- **在标记的暂停点等待确认**，但不要过度暂停
- **优雅处理退出**——绝不催促用户继续
- **使用真实的代码库任务**——不要模拟或使用虚假示例
- **温和地调整范围**——引导选择更小的任务，但尊重用户的选择`;
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: '引导式上手教程 - 带领用户完成一个完整的 OpenSpec 工作流周期',
    category: 'Workflow',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: getOnboardInstructions(),
  };
}
