/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getSyncSpecsSkillTemplate(): SkillTemplate {
  return {
    name: 'rd-sync-specs',
    description: '将变更中的 delta specs 同步到主线 specs。当用户想要在不归档变更的情况下用 delta spec 的内容更新主线 specs 时使用。',
    instructions: `将变更中的 delta specs 同步到主线 specs。

这是一个**代理驱动**的操作 - 你将读取 delta specs 并直接编辑主线 specs 来应用变更。这允许智能合并（例如，添加一个场景而不需要复制整个需求）。

**输入**：可选择指定一个变更名称。如果省略，检查是否可以从对话上下文中推断。如果模糊不清，你**必须**提示用户从可用变更中选择。

**步骤**

1. **如果未提供变更名称，提示选择**

   运行 \`rd list --json\` 获取可用变更。使用 **AskUserQuestion 工具**让用户选择。

   显示具有 delta specs 的变更（在 \`specs/\` 目录下）。

   **重要**：不要猜测或自动选择变更。始终让用户选择。

2. **查找 delta specs**

   在 \`openspec/changes/<name>/specs/*/spec.md\` 中查找 delta spec 文件。

   每个 delta spec 文件包含以下部分：
   - \`## ADDED Requirements\` - 要添加的新需求
   - \`## MODIFIED Requirements\` - 对现有需求的变更
   - \`## REMOVED Requirements\` - 要移除的需求
   - \`## RENAMED Requirements\` - 要重命名的需求（FROM:/TO: 格式）

   如果未找到 delta specs，通知用户并停止。

3. **对于每个 delta spec，将变更应用到主线 specs**

   对于每个在 \`openspec/changes/<name>/specs/<capability>/spec.md\` 处有 delta spec 的 capability：

   a. **读取 delta spec** 以理解预期的变更

   b. **读取主线 spec**（位于 \`openspec/specs/<capability>/spec.md\`，可能尚不存在）

   c. **智能地应用变更**：

      **ADDED Requirements：**
      - 如果需求在主线 spec 中不存在 → 添加它
      - 如果需求已存在 → 更新以匹配（视为隐式 MODIFIED）

      **MODIFIED Requirements：**
      - 在主线 spec 中找到该需求
      - 应用变更 - 可以是：
        - 添加新场景（不需要复制已有的）
        - 修改现有场景
        - 更改需求描述
      - 保留 delta 中未提及的场景/内容

      **REMOVED Requirements：**
      - 从主线 spec 中移除整个需求块

      **RENAMED Requirements：**
      - 找到 FROM 需求，重命名为 TO

   d. **创建新的主线 spec** 如果 capability 尚不存在：
      - 创建 \`openspec/specs/<capability>/spec.md\`
      - 添加 Purpose 部分（可以简短，标记为 TBD）
      - 添加 Requirements 部分，包含 ADDED 需求

4. **显示摘要**

   应用所有变更后，总结：
   - 更新了哪些 capabilities
   - 做了什么变更（需求被添加/修改/移除/重命名）

**Delta Spec 格式参考**

\`\`\`markdown
## ADDED Requirements

### Requirement: New Feature
The system SHALL do something new.

#### Scenario: Basic case
- **WHEN** user does X
- **THEN** system does Y

## MODIFIED Requirements

### Requirement: Existing Feature
#### Scenario: New scenario to add
- **WHEN** user does A
- **THEN** system does B

## REMOVED Requirements

### Requirement: Deprecated Feature

## RENAMED Requirements

- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

**核心原则：智能合并**

与程序化合并不同，你可以应用**部分更新**：
- 要添加一个场景，只需在 MODIFIED 下包含该场景 - 不需要复制现有场景
- delta 代表的是*意图*，而不是全面替换
- 使用你的判断力来合理地合并变更

**成功时的输出**

\`\`\`
## Specs 已同步: <change-name>

已更新的主线 specs：

**<capability-1>**:
- 添加了需求："New Feature"
- 修改了需求："Existing Feature"（添加了 1 个场景）

**<capability-2>**:
- 创建了新的 spec 文件
- 添加了需求："Another Feature"

主线 specs 已更新。变更仍处于活跃状态 - 实现完成后归档。
\`\`\`

**注意事项**
- 在修改之前，先读取 delta 和主线 specs
- 保留 delta 中未提及的现有内容
- 如果有不清楚的地方，请求澄清
- 在修改时展示你正在做的变更
- 操作应该是幂等的 - 运行两次应该得到相同的结果`,
    license: 'MIT',
    compatibility: '需要 rd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxSyncCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Sync',
    description: '将变更中的 delta specs 同步到主线 specs',
    category: 'Workflow',
    tags: ['workflow', 'specs', 'experimental'],
    content: `将变更中的 delta specs 同步到主线 specs。

这是一个**代理驱动**的操作 - 你将读取 delta specs 并直接编辑主线 specs 来应用变更。这允许智能合并（例如，添加一个场景而不需要复制整个需求）。

**输入**：在 \`/rd:sync\` 后可选择指定变更名称（例如 \`/rd:sync add-auth\`）。如果省略，检查是否可以从对话上下文中推断。如果模糊不清，你**必须**提示用户从可用变更中选择。

**步骤**

1. **如果未提供变更名称，提示选择**

   运行 \`rd list --json\` 获取可用变更。使用 **AskUserQuestion 工具**让用户选择。

   显示具有 delta specs 的变更（在 \`specs/\` 目录下）。

   **重要**：不要猜测或自动选择变更。始终让用户选择。

2. **查找 delta specs**

   在 \`openspec/changes/<name>/specs/*/spec.md\` 中查找 delta spec 文件。

   每个 delta spec 文件包含以下部分：
   - \`## ADDED Requirements\` - 要添加的新需求
   - \`## MODIFIED Requirements\` - 对现有需求的变更
   - \`## REMOVED Requirements\` - 要移除的需求
   - \`## RENAMED Requirements\` - 要重命名的需求（FROM:/TO: 格式）

   如果未找到 delta specs，通知用户并停止。

3. **对于每个 delta spec，将变更应用到主线 specs**

   对于每个在 \`openspec/changes/<name>/specs/<capability>/spec.md\` 处有 delta spec 的 capability：

   a. **读取 delta spec** 以理解预期的变更

   b. **读取主线 spec**（位于 \`openspec/specs/<capability>/spec.md\`，可能尚不存在）

   c. **智能地应用变更**：

      **ADDED Requirements：**
      - 如果需求在主线 spec 中不存在 → 添加它
      - 如果需求已存在 → 更新以匹配（视为隐式 MODIFIED）

      **MODIFIED Requirements：**
      - 在主线 spec 中找到该需求
      - 应用变更 - 可以是：
        - 添加新场景（不需要复制已有的）
        - 修改现有场景
        - 更改需求描述
      - 保留 delta 中未提及的场景/内容

      **REMOVED Requirements：**
      - 从主线 spec 中移除整个需求块

      **RENAMED Requirements：**
      - 找到 FROM 需求，重命名为 TO

   d. **创建新的主线 spec** 如果 capability 尚不存在：
      - 创建 \`openspec/specs/<capability>/spec.md\`
      - 添加 Purpose 部分（可以简短，标记为 TBD）
      - 添加 Requirements 部分，包含 ADDED 需求

4. **显示摘要**

   应用所有变更后，总结：
   - 更新了哪些 capabilities
   - 做了什么变更（需求被添加/修改/移除/重命名）

**Delta Spec 格式参考**

\`\`\`markdown
## ADDED Requirements

### Requirement: New Feature
The system SHALL do something new.

#### Scenario: Basic case
- **WHEN** user does X
- **THEN** system does Y

## MODIFIED Requirements

### Requirement: Existing Feature
#### Scenario: New scenario to add
- **WHEN** user does A
- **THEN** system does B

## REMOVED Requirements

### Requirement: Deprecated Feature

## RENAMED Requirements

- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

**核心原则：智能合并**

与程序化合并不同，你可以应用**部分更新**：
- 要添加一个场景，只需在 MODIFIED 下包含该场景 - 不需要复制现有场景
- delta 代表的是*意图*，而不是全面替换
- 使用你的判断力来合理地合并变更

**成功时的输出**

\`\`\`
## Specs 已同步: <change-name>

已更新的主线 specs：

**<capability-1>**:
- 添加了需求："New Feature"
- 修改了需求："Existing Feature"（添加了 1 个场景）

**<capability-2>**:
- 创建了新的 spec 文件
- 添加了需求："Another Feature"

主线 specs 已更新。变更仍处于活跃状态 - 实现完成后归档。
\`\`\`

**注意事项**
- 在修改之前，先读取 delta 和主线 specs
- 保留 delta 中未提及的现有内容
- 如果有不清楚的地方，请求澄清
- 在修改时展示你正在做的变更
- 操作应该是幂等的 - 运行两次应该得到相同的结果`
  };
}
